//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_MVC_ASPNET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> Fecha_Nac { get; set; }
    }
}
